# Generated by Django 4.1.2 on 2022-10-29 11:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('first_name', models.CharField(default='name', help_text='Enter your first name', max_length=50)),
                ('last_name', models.CharField(default='name', help_text='Enter your last name', max_length=50)),
                ('age', models.IntegerField(default=18, help_text='Enter your age', validators=[django.core.validators.MinValueValidator(18.0), django.core.validators.MaxValueValidator(120.0)])),
                ('primary_key', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='song', max_length=100)),
                ('date_released', models.DateField(default=datetime.datetime.today)),
                ('likes', models.IntegerField(default=0)),
                ('artiste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='lyrics', max_length=1000000)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.song')),
            ],
        ),
    ]
