# Generated by Django 4.1.2 on 2022-11-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='artist_name',
            field=models.CharField(default='name', help_text='Enter your first name', max_length=50),
        ),
    ]
